use_frameworks!

target 'DayDatePicker_Example' do
  pod 'DayDatePicker', :path => '../'

  target 'DayDatePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
